version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia # Persistent data volume
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  producer:
    build: ./producer
    container_name: producer
    depends_on:
      - rabbitmq
    environment:
      SPRING_PROFILES_ACTIVE: beta
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      QUEUE_NAME: my_queue
      EXCHANGE_NAME: my_exchange
      ROUTING_KEY: my_routing_key
    ports:
      - "8080:8080" # Expose producer service on port 8080

volumes:
  rabbitmq_data:
